// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package logitowwindowsnative;

@net.sf.jni4net.attributes.ClrInterface
public interface DeviceEventReceiver {
    
    //<generated-interface>
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    void OnDeviceDiscovered(java.lang.String uuid);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    void OnDeviceLost(java.lang.String uuid);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    void OnScanStarted();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    void OnScanStopped();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    void OnDeviceConnected(java.lang.String uuid);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    void OnDeviceDisconnected(java.lang.String uuid);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;[B)V")
    void OnBlockDataReceived(java.lang.String uuid, byte[] data);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;F)V")
    void OnBatteryInfoReceived(java.lang.String uuid, float battery);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LWindows/Devices/Bluetooth/GenericAttributeProfile/GattCommunicationStatus;)V")
    void OnConnectionError(java.lang.String uuid, system.Enum communicationStatus);

    void OnConnectionError(String uuid, Enum communicationStatus);
    //</generated-interface>
}
