/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class com_logitow_bridge_communication_platform_mac_MacDeviceManager */

#ifndef _Included_com_logitow_bridge_communication_platform_mac_MacDeviceManager
#define _Included_com_logitow_bridge_communication_platform_mac_MacDeviceManager
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_logitow_bridge_communication_platform_mac_MacDeviceManager
     * Method:    setup
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_com_logitow_bridge_communication_platform_mac_MacDeviceManager_setup
    (JNIEnv *, jclass);
    
    /*
     * Class:     com_logitow_bridge_communication_platform_mac_MacDeviceManager
     * Method:    getNativeBluetoothState
     * Signature: ()I
     */
    JNIEXPORT jint JNICALL Java_com_logitow_bridge_communication_platform_mac_MacDeviceManager_getNativeBluetoothState
    (JNIEnv *, jclass);
    
    /*
     * Class:     com_logitow_bridge_communication_platform_mac_MacDeviceManager
     * Method:    startScanDevice
     * Signature: ()Z
     */
    JNIEXPORT jboolean JNICALL Java_com_logitow_bridge_communication_platform_mac_MacDeviceManager_startScanDevice
    (JNIEnv *, jclass);
    
    /*
     * Class:     com_logitow_bridge_communication_platform_mac_MacDeviceManager
     * Method:    stopScanDevice
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_com_logitow_bridge_communication_platform_mac_MacDeviceManager_stopScanDevice
    (JNIEnv *, jclass);
    
    /*
     * Class:     com_logitow_bridge_communication_platform_mac_MacDeviceManager
     * Method:    disconnect
     * Signature: (Ljava/lang/String;)V
     */
    JNIEXPORT void JNICALL Java_com_logitow_bridge_communication_platform_mac_MacDeviceManager_disconnect
    (JNIEnv *, jclass, jstring);
    
    
    /*
     * Class:     com_logitow_bridge_communication_platform_mac_MacDeviceManager
     * Method:    writeToGetVoltage
     * Signature: (Ljava/lang/String;)V
     */
    JNIEXPORT jboolean JNICALL Java_com_logitow_bridge_communication_platform_mac_MacDeviceManager_writeToGetVoltage
    (JNIEnv *, jclass, jstring);

    
#ifdef __cplusplus
}
#endif
#endif
